CREATE TABLE HospitalClass
(
ClassCode VARCHAR2(100) PRIMARY KEY,
Name VARCHAR2(100)
);

CREATE TABLE Grade
(
GradeCode VARCHAR2(100) PRIMARY KEY,
Name VARCHAR2(100)
);

CREATE TABLE Hospital
(
HospitalCode VARCHAR2(100) PRIMARY KEY,
Name VARCHAR2(100),
ClassCode VARCHAR2(100) REFERENCES HospitalClass(ClassCode),
GradeCode VARCHAR2(100) REFERENCES Grade(GradeCode),
CountryCode VARCHAR2(10) REFERENCES Country(Country_Code),
CityCode VARCHAR2(10) REFERENCES City(CityCode)
BedNum VARCHAR2(100) NOT NULL,
HP VARCHAR2(100) NOT NULL
);











