CREATE TABLE MedicalChart
(
ChartNum VARCHAR2(100) PRIMARY KEY,
ChartDay DATE,
DoctorID VARCHAR2(100) REFERENCES Doctor(DoctorID),
NurseID VARCHAR2(100) REFERENCES Nurse(NurseID),
PatientID VARCHAR2(100) REFERENCES Patient(PatientID),
MajorCode VARCHAR2(100) REFERENCES Patient(MajorCode),
Symptom VARCHAR2(100) NOT NULL,
Disease VARCHAR2(100) NOT NULL,
TreatmentPlan VARCHAR2(100) NOT NULL,
Recipe VARCHAR2(100) NOT NULL
);

