--메뉴 분류코드 테이블
CREATE TABLE C_MENU_CODE
(
M_CODE VARCHAR2(3) PRIMARY KEY,
M_CDNM VARCHAR2(100) NOT NULL
);
COMMENT ON TABLE C_MENU_CODE IS '메뉴 분류 코드 테이블';
COMMENT ON COLUMN C_MENU_CODE.M_CODE IS '메뉴 분류코드';
COMMENT ON COLUMN C_MENU_CODE.M_CDNM IS '메뉴 분류명';

INSERT INTO c_menu_code VALUES('COF', '커피');
INSERT INTO c_menu_code VALUES('BEV', '음료');
INSERT INTO c_menu_code VALUES('TEA', '차');
INSERT INTO c_menu_code VALUES('DES', '디저트');
INSERT INTO c_menu_code VALUES('ADD', '추가');
INSERT INTO c_menu_code VALUES('PRO', '프로모션');
INSERT INTO c_menu_code VALUES('SEA', '시즌');


--메뉴 테이블
CREATE TABLE C_MENU
(
MENU_ID VARCHAR2(30) PRIMARY KEY,
MENU_CODE VARCHAR2(3) NOT NULL,
MENU_NAME VARCHAR2(100) NOT NULL,
MENU_PRICE NUMBER NOT NULL,
MENU_STOCK NUMBER DEFAULT 0
);

ALTER TABLE C_MENU 
ADD CONSTRAINT FK_MCD FOREIGN KEY(MENU_CODE) REFERENCES C_MENU_CODE(M_CODE);

COMMENT ON TABLE C_MENU IS '메뉴 테이블';
COMMENT ON COLUMN C_MENU.MENU_CODE IS '메뉴 분류코드';
COMMENT ON COLUMN C_MENU.MENU_ID IS '메뉴 ID';
COMMENT ON COLUMN C_MENU.MENU_NAME IS '메뉴 이름';
COMMENT ON COLUMN C_MENU.MENU_PRICE IS '메뉴 가격';
COMMENT ON COLUMN C_MENU.MENU_STOCK IS '수량';

--주문 테이블
CREATE TABLE C_ORDER
(
ORDER_ID VARCHAR2(30) PRIMARY KEY,
ORDER_USERID VARCHAR2(30) REFERENCES USERS(USER_ID) NOT NULL,
ORDER_DATE DATE DEFAULT SYSDATE,
ORDER_PAYMENT_TYPE VARCHAR2(10) NOT NULL,
ORDER_TOTAL_PRICE NUMBER DEFAULT 0
);

COMMENT ON TABLE C_ORDER IS '주문테이블';
COMMENT ON COLUMN C_ORDER.ORDER_ID IS '주문번호';
COMMENT ON COLUMN C_ORDER.ORDER_USERID IS '주문 회원 ID';
COMMENT ON COLUMN C_ORDER.ORDER_DATE IS '주문 일자';
COMMENT ON COLUMN C_ORDER.ORDER_PAYMENT_TYPE IS '결제 방식';
COMMENT ON COLUMN C_ORDER.ORDER_TOTAL_PRICE IS '결제 금액';

--상세 주문 내역 테이블
CREATE TABLE C_DETAIL_ORDER
(
DETAIL_ORDER_ID VARCHAR2(30) PRIMARY KEY,
ORDER_ID VARCHAR2(30) REFERENCES C_ORDER(ORDER_ID) NOT NULL,
ORDER_MENU_ID VARCHAR2(30) REFERENCES C_MENU(MENU_ID) NOT NULL,
ORDER_STOCK NUMBER NOT NULL
);

COMMENT ON TABLE C_DETAIL_ORDER IS '주문 내역 테이블';
COMMENT ON COLUMN C_DETAIL_ORDER.DETAIL_ORDER_ID IS '주문내역ID';
COMMENT ON COLUMN C_DETAIL_ORDER.ORDER_ID IS '주문 회원 ID';
COMMENT ON COLUMN C_DETAIL_ORDER.ORDER_MENU_ID IS '주문 메뉴 ID';
COMMENT ON COLUMN C_DETAIL_ORDER.ORDER_STOCK IS '주문 수량';

--재고 관리 테이블
CREATE TABLE C_MANAGE_STOCK
(
MANAGE_ID VARCHAR2(30) PRIMARY KEY,
MANAGE_MN_ID VARCHAR2(30) REFERENCES C_MENU(MENU_ID),
MANAGE_UNIT_PRICE NUMBER NOT NULL,
MANAGE_ENTER_QUANTITY NUMBER NOT NULL,
MANAGE_STOCK NUMBER DEFAULT 0,
MANAGE_INPUT_DATE DATE NOT NULL,
MANAGE_EXPIRY_DATE DATE NOT NULL
);

COMMENT ON TABLE C_MANAGE_STOCK IS '재고 관리 테이블';
COMMENT ON COLUMN C_MANAGE_STOCK.MANAGE_ID IS '재고관리 ID';
COMMENT ON COLUMN C_MANAGE_STOCK.MANAGE_MN_ID IS '메뉴 ID';
COMMENT ON COLUMN C_MANAGE_STOCK.MANAGE_UNIT_PRICE IS '메뉴 단가';
COMMENT ON COLUMN C_MANAGE_STOCK.MANAGE_ENTER_QUANTITY IS '입고 수량';
COMMENT ON COLUMN C_MANAGE_STOCK.MANAGE_STOCK IS '재고 수량';
COMMENT ON COLUMN C_MANAGE_STOCK.MANAGE_INPUT_DATE IS '입고 날짜';
COMMENT ON COLUMN C_MANAGE_STOCK.MANAGE_EXPIRY_DATE IS '소비기한 날짜';


--쿠폰 테이블
CREATE TABLE C_COUPON
(
COUPON_ID VARCHAR2(30) PRIMARY KEY,
COUPON_NAME VARCHAR2(100) NOT NULL,
COUPON_DC_RATE NUMBER,
COUPON_DC_PRICE NUMBER,
COUPON_PERIOD DATE NOT NULL
);

COMMENT ON TABLE C_COUPON IS '쿠폰 테이블';
COMMENT ON COLUMN C_COUPON.COUPON_ID IS '쿠폰 ID';
COMMENT ON COLUMN C_COUPON.COUPON_NAME IS '쿠폰명';
COMMENT ON COLUMN C_COUPON.COUPON_DC_RATE IS '할인률';
COMMENT ON COLUMN C_COUPON.COUPON_DC_PRICE IS '할인금액';
COMMENT ON COLUMN C_COUPON.COUPON_PERIOD IS '사용기간';

--보유 쿠폰 관리 테이블
CREATE TABLE C_MEMBERSHIP
(
MEMBERSHIP_ID VARCHAR2(30) PRIMARY KEY,
MEMBERSHIP_USERID VARCHAR2(100) REFERENCES USERS(USER_ID),
MEMBERSHIP_COUPONID VARCHAR2(30) REFERENCES C_COUPON(COUPON_ID)
);

COMMENT ON TABLE C_MEMBERSHIP IS '보유 쿠폰 관리 테이블';
COMMENT ON COLUMN C_MEMBERSHIP.MEMBERSHIP_ID IS '멤버십 ID';
COMMENT ON COLUMN C_MEMBERSHIP.MEMBERSHIP_USERID IS '회원 ID';
COMMENT ON COLUMN C_MEMBERSHIP.MEMBERSHIP_COUPONID IS '보유 쿠폰 ID';

